---
- name: Configurar Servidores Web Ubuntu con Soporte PHP
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: Forzar DNS de Google de forma temporal para permitir el apt update
      ansible.builtin.shell: |
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
      become: true
      changed_when: false

    - name: Instalar Apache
      apt:
        name:
          - apache2
        state: present
        update_cache: yes
    
    - name: Asegurar que Apache esté encendido y habilitado
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Crear página de prueba HTML (con hostname)
      copy:
        content: "<h1>Hola desde {{ ansible_hostname }} (Entorno de David)</h1>"
        dest: /var/www/html/index.html
        mode: '0644'

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted

