- name: Configurar Balanceador de Carga HAProxy en Local
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Instalar HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configurar el archivo haproxy.cfg
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          frontend http_front
              bind *:80
              default_backend http_back

          backend http_back
              balance roundrobin
              server apache1 192.168.2.10:80 check
              server apache2 192.168.2.11:80 check
      notify: Reiniciar HAProxy

    - name: Asegurar que HAProxy esta corriendo y habilitado
      systemd:
        name: haproxy
        state: started
        enabled: yes
