---
# 1. CONFIGURACIÓN DEL SERVIDOR ZABBIX
- name: Configurar Servidor Zabbix con DB Remota
  hosts: localhost
  become: true
  tasks:
    - name: Forzar DNS de Google de forma temporal para permitir el apt update
      ansible.builtin.shell: |
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
      changed_when: false

    - name: Añadir repositorio oficial de Zabbix 7.0 (Ubuntu 24.04)
      apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb
        state: present

    - name: Instalar paquetes de Zabbix Server y Frontend
      apt:
        name: 
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - mariadb-client # Necesario para importar el esquema a la DB remota
        state: present
        update_cache: yes

    ---
- name: Lanzar comandos manuales para crear la DB de Zabbix
  hosts: localhost
  become: yes

  tasks:
    - name: 1. Ejecutar el CREATE DATABASE a mano
      shell: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS zabbix CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"

    - name: 2. Ejecutar el CREATE USER a mano (Contraseña: zabbix123)
      shell: |
        mysql -u root -e "CREATE USER IF NOT EXISTS 'zabbix'@'%' IDENTIFIED BY 'zabbix123';"

    - name: 3. Asignar todos los PRIVILEGES a mano
      shell: |
        mysql -u root -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'%';"

    - name: 4. Lanzar el FLUSH PRIVILEGES definitivo
      shell: |
        mysql -u root -e "FLUSH PRIVILEGES;"
