[pfsense]
192.168.0.50

[haproxy]
192.168.2.20

[mariadb_primary]
192.168.1.30

[mariadb_slave]
192.168.1.31

[db_servers]
192.168.1.30
192.168.1.31

[webservers]
192.168.2.10
192.168.2.11 

[monitoring]
192.168.1.50

[lan_servers]
192.168.1.30
192.168.1.31
192.168.1.50

[dmz_servers]
192.168.2.10
192.168.2.11
192.168.2.20

[resto]
192.168.2.10
192.168.2.11
192.168.2.20
192.168.1.30
192.168.1.31

[pfsense:vars]
ansible_user=admin
ansible_password=Templario066268
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_shell_type=csh

[web_servers:vars]
ansible_user=ubuntu
ansible_password=1234
ansible_become_password=1234
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[lan_servers:vars]
ansible_user=ubuntu
ansible_password=1234
ansible_sudo_pass=1234
ansible_python_interpreter=/usr/bin/python3

[dmz_servers:vars]
ansible_user=ubuntu
ansible_password=1234
ansible_sudo_pass=1234
ansible_python_interpreter=/usr/bin/python3
